FROM rust:1.84-alpine3.20

WORKDIR /app

RUN apk add build-base openssl-dev openssl-libs-static libssl3 libcrypto3

RUN cargo install cargo-watch

COPY Cargo.toml Cargo.lock ./
RUN cargo fetch

COPY . .

EXPOSE 8000
CMD ["cargo", "watch", "-x", "run -- --bind 0.0.0.0 --port 8000"]
